// Full list of Singapore primary schools used for the Add / Edit Student form.
// Suffixes like " - Boys only, Affiliated" from the original MOE listing are
// stripped so that the stored value is a clean school name.
const rawPrimarySchools = [
  'Admiralty Primary School',
  'Ahmad Ibrahim Primary School',
  'Ai Tong School',
  'Alexandra Primary School',
  'Anchor Green Primary School',
  'Anderson Primary School',
  'Ang Mo Kio Primary School',
  'Anglo-Chinese School (Junior)',
  'Anglo-Chinese School (Primary)',
  'Angsana Primary School',
  'Beacon Primary School',
  'Bedok Green Primary School',
  'Bendemeer Primary School',
  'Blangah Rise Primary School',
  'Boon Lay Garden Primary School',
  'Bukit Panjang Primary School',
  'Bukit Timah Primary School',
  'Bukit View Primary School',
  'Canberra Primary School',
  'Canossa Catholic Primary School',
  'Cantonment Primary School',
  'Casuarina Primary School',
  'Catholic High School',
  'Cedar Primary School',
  'Changkat Primary School',
  'CHIJ (Katong) Primary',
  'CHIJ (Kellock)',
  'CHIJ Our Lady of Good Counsel',
  'CHIJ Our Lady of the Nativity',
  'CHIJ Our Lady Queen of Peace',
  'CHIJ Primary (Toa Payoh)',
  "CHIJ St. Nicholas Girls' School",
  'Chongfu School',
  'Chongzheng Primary School',
  'Chua Chu Kang Primary School',
  'Clementi Primary School',
  'Compassvale Primary School',
  'Concord Primary School',
  'Corporation Primary School',
  'Damai Primary School',
  'Dazhong Primary School',
  'De La Salle School',
  'East Spring Primary School',
  'Edgefield Primary School',
  'Elias Park Primary School',
  'Endeavour Primary School',
  'Eunos Primary School',
  'Evergreen Primary School',
  'Fairfield Methodist School (Primary)',
  'Farrer Park Primary School',
  'Fengshan Primary School',
  'Fern Green Primary School',
  'Fernvale Primary School',
  'First Toa Payoh Primary School',
  'Frontier Primary School',
  'Fuchun Primary School',
  'Fuhua Primary School',
  'Gan Eng Seng Primary School',
  'Geylang Methodist School (Primary)',
  'Gongshang Primary School',
  'Greendale Primary School',
  'Greenridge Primary School',
  'Greenwood Primary School',
  'Guangyang Primary School',
  "Haig Girls' School",
  'Henry Park Primary School',
  "Holy Innocents' Primary School",
  'Hong Wen School',
  'Horizon Primary School',
  'Hougang Primary School',
  'Huamin Primary School',
  'Innova Primary School',
  'Jiemin Primary School',
  'Jing Shan Primary School',
  'Junyuan Primary School',
  'Jurong Primary School',
  'Jurong West Primary School',
  'Juying Primary School',
  'Keming Primary School',
  'Kheng Cheng School',
  'Kong Hwa School',
  'Kranji Primary School',
  'Kuo Chuan Presbyterian Primary School',
  'Lakeside Primary School',
  'Lianhua Primary School',
  'Maha Bodhi School',
  'Maris Stella High School',
  'Marsiling Primary School',
  'Marymount Convent School',
  'Mayflower Primary School',
  'Mee Toh School',
  'Meridian Primary School',
  "Methodist Girls' School (Primary)",
  'Montfort Junior School',
  'Nan Chiau Primary School',
  'Nan Hua Primary School',
  'Nanyang Primary School',
  'Naval Base Primary School',
  'New Town Primary School',
  'Ngee Ann Primary School',
  'North Spring Primary School',
  'North View Primary School',
  'North Vista Primary School',
  'Northland Primary School',
  'Northoaks Primary School',
  'Northshore Primary School',
  'Oasis Primary School',
  'Opera Estate Primary School',
  'Palm View Primary School',
  'Park View Primary School',
  'Pasir Ris Primary School',
  "Paya Lebar Methodist Girls' School (Primary)",
  'Pei Chun Public School',
  'Pei Hwa Presbyterian Primary School',
  'Pei Tong Primary School',
  'Peiying Primary School',
  'Pioneer Primary School',
  'Poi Ching School',
  'Princess Elizabeth Primary School',
  'Punggol Cove Primary School',
  'Punggol Green Primary School',
  'Punggol Primary School',
  'Punggol View Primary School',
  'Qifa Primary School',
  'Qihua Primary School',
  'Queenstown Primary School',
  'Radin Mas Primary School',
  "Raffles Girls' Primary School",
  'Red Swastika School',
  'River Valley Primary School',
  'Riverside Primary School',
  'Rivervale Primary School',
  'Rosyth School',
  'Rulang Primary School',
  'Sembawang Primary School',
  'Seng Kang Primary School',
  'Sengkang Green Primary School',
  'Shuqun Primary School',
  'Si Ling Primary School',
  "Singapore Chinese Girls' Primary School",
  'South View Primary School',
  'Springdale Primary School',
  "St. Andrew's Junior School",
  "St. Anthony's Canossian Primary School",
  "St. Anthony's Primary School",
  "St. Gabriel's Primary School",
  "St. Hilda's Primary School",
  "St. Joseph's Institution Junior",
  "St. Margaret's School (Primary)",
  "St. Stephen's School",
  'Stamford Primary School',
  'Tampines North Primary School',
  'Tampines Primary School',
  'Tanjong Katong Primary School',
  'Tao Nan School',
  'Teck Ghee Primary School',
  'Teck Whye Primary School',
  'Telok Kurau Primary School',
  'Temasek Primary School',
  'Townsville Primary School',
  'Unity Primary School',
  'Valour Primary School',
  'Waterway Primary School',
  'Wellington Primary School',
  'West Grove Primary School',
  'West Spring Primary School',
  'West View Primary School',
  'Westwood Primary School',
  'White Sands Primary School',
  'Woodgrove Primary School',
  'Woodlands Primary School',
  'Woodlands Ring Primary School',
  'Xinghua Primary School',
  'Xingnan Primary School',
  'Xinmin Primary School',
  'Xishan Primary School',
  'Yangzheng Primary School',
  'Yew Tee Primary School',
  'Yio Chu Kang Primary School',
  'Yishun Primary School',
  'Yu Neng Primary School',
  'Yuhua Primary School',
  'Yumin Primary School',
  'Zhangde Primary School',
  'Zhenghua Primary School',
  'Zhonghua Primary School'
]

const rawSecondarySchools = [
  'ADMIRALTY SECONDARY SCHOOL',
  'AHMAD IBRAHIM SECONDARY SCHOOL',
  'ANDERSON SECONDARY SCHOOL',
  'ANG MO KIO SECONDARY SCHOOL',
  'ANGLICAN HIGH SCHOOL',
  'ANGLO-CHINESE SCHOOL (BARKER ROAD)',
  'ANGLO-CHINESE SCHOOL (INDEPENDENT)',
  'ASSUMPTION ENGLISH SCHOOL',
  'BARTLEY SECONDARY SCHOOL',
  'BEATTY SECONDARY SCHOOL',
  'BEDOK GREEN SECONDARY SCHOOL',
  'BEDOK SOUTH SECONDARY SCHOOL',
  'BEDOK VIEW SECONDARY SCHOOL',
  'BENDEMEER SECONDARY SCHOOL',
  'BOON LAY SECONDARY SCHOOL',
  'BOWEN SECONDARY SCHOOL',
  'BROADRICK SECONDARY SCHOOL',
  'BUKIT BATOK SECONDARY SCHOOL',
  'BUKIT MERAH SECONDARY SCHOOL',
  'BUKIT PANJANG GOVT. HIGH SCHOOL',
  'BUKIT VIEW SECONDARY SCHOOL',
  'CANBERRA SECONDARY SCHOOL',
  'CATHOLIC HIGH SCHOOL',
  "CEDAR GIRLS' SECONDARY SCHOOL",
  'CHANGKAT CHANGI SECONDARY SCHOOL',
  'CHIJ KATONG CONVENT',
  'CHIJ SECONDARY (TOA PAYOH)',
  "CHIJ ST. JOSEPH'S CONVENT",
  "CHIJ ST. NICHOLAS GIRLS' SCHOOL",
  "CHIJ ST. THERESA'S CONVENT",
  'CHRIST CHURCH SECONDARY SCHOOL',
  'CHUA CHU KANG SECONDARY SCHOOL',
  'CHUNG CHENG HIGH SCHOOL (MAIN)',
  'CHUNG CHENG HIGH SCHOOL (YISHUN)',
  'CLEMENTI TOWN SECONDARY SCHOOL',
  'COMMONWEALTH SECONDARY SCHOOL',
  'COMPASSVALE SECONDARY SCHOOL',
  "CRESCENT GIRLS' SCHOOL",
  'DAMAI SECONDARY SCHOOL',
  'DEYI SECONDARY SCHOOL',
  'DUNEARN SECONDARY SCHOOL',
  'DUNMAN HIGH SCHOOL',
  'DUNMAN SECONDARY SCHOOL',
  'EAST SPRING SECONDARY SCHOOL',
  'EDGEFIELD SECONDARY SCHOOL',
  'EVERGREEN SECONDARY SCHOOL',
  'FAIRFIELD METHODIST SCHOOL (SECONDARY)',
  'FAJAR SECONDARY SCHOOL',
  'FUCHUN SECONDARY SCHOOL',
  'FUHUA SECONDARY SCHOOL',
  'GAN ENG SENG SCHOOL',
  'GEYLANG METHODIST SCHOOL (SECONDARY)',
  'GREENDALE SECONDARY SCHOOL',
  'GREENRIDGE SECONDARY SCHOOL',
  'GUANGYANG SECONDARY SCHOOL',
  'HAI SING CATHOLIC SCHOOL',
  'HILLGROVE SECONDARY SCHOOL',
  "HOLY INNOCENTS' HIGH SCHOOL",
  'HOUGANG SECONDARY SCHOOL',
  'HUA YI SECONDARY SCHOOL',
  'HWA CHONG INSTITUTION',
  'JUNYUAN SECONDARY SCHOOL',
  'JURONG SECONDARY SCHOOL',
  'JURONG WEST SECONDARY SCHOOL',
  'JURONGVILLE SECONDARY SCHOOL',
  'JUYING SECONDARY SCHOOL',
  'KENT RIDGE SECONDARY SCHOOL',
  'KRANJI SECONDARY SCHOOL',
  'KUO CHUAN PRESBYTERIAN SECONDARY SCHOOL',
  'LOYANG VIEW SECONDARY SCHOOL',
  'MANJUSRI SECONDARY SCHOOL',
  'MARIS STELLA HIGH SCHOOL',
  'MARSILING SECONDARY SCHOOL',
  'MAYFLOWER SECONDARY SCHOOL',
  'MERIDIAN SECONDARY SCHOOL',
  "METHODIST GIRLS' SCHOOL (SECONDARY)",
  'MONTFORT SECONDARY SCHOOL',
  'NAN CHIAU HIGH SCHOOL',
  'NAN HUA HIGH SCHOOL',
  "NANYANG GIRLS' HIGH SCHOOL",
  'NATIONAL JUNIOR COLLEGE',
  'NAVAL BASE SECONDARY SCHOOL',
  'NEW TOWN SECONDARY SCHOOL',
  'NGEE ANN SECONDARY SCHOOL',
  'NORTH VISTA SECONDARY SCHOOL',
  'NORTHBROOKS SECONDARY SCHOOL',
  'NORTHLAND SECONDARY SCHOOL',
  'ORCHID PARK SECONDARY SCHOOL',
  'OUTRAM SECONDARY SCHOOL',
  'PASIR RIS CREST SECONDARY SCHOOL',
  'PASIR RIS SECONDARY SCHOOL',
  "PAYA LEBAR METHODIST GIRLS' SCHOOL (SEC)",
  'PEI HWA SECONDARY SCHOOL',
  'PEICAI SECONDARY SCHOOL',
  'PEIRCE SECONDARY SCHOOL',
  'PING YI SECONDARY SCHOOL',
  'PRESBYTERIAN HIGH SCHOOL',
  'PUNGGOL SECONDARY SCHOOL',
  'QUEENSTOWN SECONDARY SCHOOL',
  'QUEENSWAY SECONDARY SCHOOL',
  "RAFFLES GIRLS' SCHOOL (SECONDARY)",
  'RAFFLES INSTITUTION',
  'REGENT SECONDARY SCHOOL',
  'RIVER VALLEY HIGH SCHOOL',
  'RIVERSIDE SECONDARY SCHOOL',
  'SEMBAWANG SECONDARY SCHOOL',
  'SENG KANG SECONDARY SCHOOL',
  'SERANGOON GARDEN SECONDARY SCHOOL',
  'SERANGOON SECONDARY SCHOOL',
  "SINGAPORE CHINESE GIRLS' SCHOOL",
  'SPRINGFIELD SECONDARY SCHOOL',
  "ST. ANDREW'S SECONDARY SCHOOL",
  "ST. ANTHONY'S CANOSSIAN SECONDARY SCHOOL",
  "ST. GABRIEL'S SECONDARY SCHOOL",
  "ST. HILDA'S SECONDARY SCHOOL",
  "ST. JOSEPH'S INSTITUTION",
  "ST. MARGARET'S SECONDARY SCHOOL",
  "ST. PATRICK'S SCHOOL",
  'SWISS COTTAGE SECONDARY SCHOOL',
  'TAMPINES SECONDARY SCHOOL',
  'TANGLIN SECONDARY SCHOOL',
  "TANJONG KATONG GIRLS' SCHOOL",
  'TANJONG KATONG SECONDARY SCHOOL',
  'TECK WHYE SECONDARY SCHOOL',
  'TEMASEK JUNIOR COLLEGE',
  'TEMASEK SECONDARY SCHOOL',
  'UNITY SECONDARY SCHOOL',
  'VICTORIA SCHOOL',
  'WEST SPRING SECONDARY SCHOOL',
  'WESTWOOD SECONDARY SCHOOL',
  'WHITLEY SECONDARY SCHOOL',
  'WOODGROVE SECONDARY SCHOOL',
  'WOODLANDS RING SECONDARY SCHOOL',
  'WOODLANDS SECONDARY SCHOOL',
  'XINMIN SECONDARY SCHOOL',
  'YIO CHU KANG SECONDARY SCHOOL',
  'YISHUN SECONDARY SCHOOL',
  'YISHUN TOWN SECONDARY SCHOOL',
  'YUAN CHING SECONDARY SCHOOL',
  'YUHUA SECONDARY SCHOOL',
  'YUYING SECONDARY SCHOOL',
  'ZHENGHUA SECONDARY SCHOOL',
  'ZHONGHUA SECONDARY SCHOOL'
]

function dedupeAndSort(list) {
  const seen = new Set()
  return list
    .map((s) => s.trim())
    .filter((s) => {
      if (!s) return false
      const key = s.toUpperCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .sort((a, b) => a.localeCompare(b))
}

export const PRIMARY_SCHOOLS = dedupeAndSort(rawPrimarySchools)
export const SECONDARY_SCHOOLS = dedupeAndSort(rawSecondarySchools)

// Keep aliases used by the feature spec.
export const primarySchools = PRIMARY_SCHOOLS
export const secondarySchools = SECONDARY_SCHOOLS

// Returns the school list that matches a student level.
// Levels starting with "Pri" return primary schools, levels starting with
// "Sec" return secondary schools. Unknown or empty levels return an empty
// list so callers can use this to drive a "Select level first" UI state.
export function getSchoolsByLevel(level) {
  if (!level) return []
  const trimmed = String(level).trim()
  if (!trimmed) return []
  const lower = trimmed.toLowerCase()
  if (lower.startsWith('pri')) return PRIMARY_SCHOOLS
  if (lower.startsWith('sec')) return SECONDARY_SCHOOLS
  return []
}

export default SECONDARY_SCHOOLS
